# Generated by Django 3.2.6 on 2021-09-07 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rest_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('comment', models.CharField(blank=True, max_length=120, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='rest_admin.menutable')),
                ('table_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_id', to='rest_admin.table')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('comment', models.CharField(blank=True, max_length=120, null=True)),
                ('ordered', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=100)),
                ('total_bill', models.IntegerField(blank=True, null=True)),
                ('item', models.ManyToManyField(to='restaurant.OrderItem')),
                ('table_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_table_id', to='rest_admin.table')),
            ],
        ),
    ]
