# Generated by Django 3.2.6 on 2021-10-01 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_admin', '0004_inventory_date'),
        ('restaurant', '0002_parcel_customer_parcel_order_parcel_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallWaiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.BooleanField(default=False)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_waiter', to='rest_admin.table')),
            ],
        ),
    ]
